# Azure Pipeline that run basic continuous integration on a Terraform project
# This makes sure the pipeline is triggered every time code is pushed in the validation-testing example source, on all branches.
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - 'MyIaCPortfolio/containerapp-acr/*'

variables:
  serviceConnection: 'ServiceConnectiontoDevOps'
  azureLocation: 'canadacentral'

stages:
  - stage: TerraformContinuousIntegration 
    displayName: Terraform Module - CI
    jobs:
    - job: TerraformContinuousIntegrationJob
      displayName: TerraformContinuousIntegration - CI Job - Backend creation
      pool:
        name: MySelfHosted   
      steps:
      - checkout: self
      - script: dir
        displayName: List files in workspace

      - task: TerraformInstaller@2
        inputs:
          terraformVersion: '1.13.3'
      - task: TerraformCLI@2
        inputs:
          command: 'version'
          allowTelemetryCollection: true
      - task: TerraformCLI@2
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/create-backend'
          allowTelemetryCollection: true
        displayName: "Initialize the template for the backend"
      - task: TerraformCLI@2
        inputs:
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/create-backend'
          allowTelemetryCollection: true
          publishPlanResults: 'plan.out'
        displayName: "Plan the deployment"

      - task: TerraformCLI@2
        inputs:
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/create-backend'
          commandOptions: 'plan.out'
          allowTelemetryCollection: true
        displayName: "Deploy the resources"

